# Generated by Django 3.0.8 on 2020-08-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(default=1, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='season',
            field=models.ManyToManyField(blank=True, to='accounts.Seasons'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(default='guitar', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(default='nayak', max_length=100, null=True),
        ),
    ]
