# Generated by Django 4.0.6 on 2023-04-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_musician_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
